<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8</TargetFramework>
    <Nullable>enable</Nullable>
    
    <!-- NuGet Package Properties -->
    <PackageId>TechFood.Shared.Worker</PackageId>
    <Version>1.0.0</Version>
    <Authors>TechChallenge-Team</Authors>
    <Company>TechChallenge</Company>
    <Description>TechFood Shared Worker - Recursos de worker compartilhados</Description>
    <PackageTags>techfood;worker;shared</PackageTags>
    <RepositoryUrl>https://github.com/TechChallenge-Team/techfood-shared</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TechFood.Shared.Infra\TechFood.Shared.Infra.csproj" />
  </ItemGroup>

</Project>
