//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechFood.Shared.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Exceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exceptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TechFood.Shared.Domain.Resources.Exceptions", typeof(Exceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The category file image cannot be empty.
        /// </summary>
        public static string Category_ThrowFileImageIsEmpty {
            get {
                return ResourceManager.GetString("Category_ThrowFileImageIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category order must be greater than or equal to 0..
        /// </summary>
        public static string Category_ThrowIndexIsLessThanZero {
            get {
                return ResourceManager.GetString("Category_ThrowIndexIsLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The category name cannot be empty.
        /// </summary>
        public static string Category_ThrowNameIsEmpty {
            get {
                return ResourceManager.GetString("Category_ThrowNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Document CPF is invalid.
        /// </summary>
        public static string Customer_ThrowDocumentCPFInvalid {
            get {
                return ResourceManager.GetString("Customer_ThrowDocumentCPFInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Invalid.
        /// </summary>
        public static string Customer_ThrowEmailInvalid {
            get {
                return ResourceManager.GetString("Customer_ThrowEmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment amount is not equal to the order total amount..
        /// </summary>
        public static string Order_AmountIsNotEqualOrderAmount {
            get {
                return ResourceManager.GetString("Order_AmountIsNotEqualOrderAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add items to an order that is not in the Pending status..
        /// </summary>
        public static string Order_CannotAddItemToNonPendingStatus {
            get {
                return ResourceManager.GetString("Order_CannotAddItemToNonPendingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot apply discount to an order that is not in the Pending status..
        /// </summary>
        public static string Order_CannotApplyDiscountToNonPendingStatus {
            get {
                return ResourceManager.GetString("Order_CannotApplyDiscountToNonPendingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot deliver an order that is not in the Ready status..
        /// </summary>
        public static string Order_CannotDeliverToNonReadyStatus {
            get {
                return ResourceManager.GetString("Order_CannotDeliverToNonReadyStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot prepare an order that is not in the Received status..
        /// </summary>
        public static string Order_CannotPrepareToNonReceivedStatus {
            get {
                return ResourceManager.GetString("Order_CannotPrepareToNonReceivedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot ready an order that is not in the InPreparation status..
        /// </summary>
        public static string Order_CannotReadyToNonInPreparationStatus {
            get {
                return ResourceManager.GetString("Order_CannotReadyToNonInPreparationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot receive an order that is not in the Pending status..
        /// </summary>
        public static string Order_CannotReceiveToNonPendingStatus {
            get {
                return ResourceManager.GetString("Order_CannotReceiveToNonPendingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot remove items from an order that is not in the Pending status..
        /// </summary>
        public static string Order_CannotRemoveItemToNonPendingStatus {
            get {
                return ResourceManager.GetString("Order_CannotRemoveItemToNonPendingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount cannot be negative..
        /// </summary>
        public static string Order_DiscountCannotBeNegative {
            get {
                return ResourceManager.GetString("Order_DiscountCannotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order item not found..
        /// </summary>
        public static string Order_ItemNotFound {
            get {
                return ResourceManager.GetString("Order_ItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment cannot be null..
        /// </summary>
        public static string Order_PaymentIsNull {
            get {
                return ResourceManager.GetString("Order_PaymentIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ProductId is not valid.
        /// </summary>
        public static string OrderItem_ThrowProductIdIsInvalid {
            get {
                return ResourceManager.GetString("OrderItem_ThrowProductIdIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The OrdemItem quantity have be greater than zero.
        /// </summary>
        public static string OrderItem_ThrowQuantityGreaterThanZero {
            get {
                return ResourceManager.GetString("OrderItem_ThrowQuantityGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The orderItem UnitPrice have be greater than zero.
        /// </summary>
        public static string OrderItem_ThrowUnitPriceGreaterThanZero {
            get {
                return ResourceManager.GetString("OrderItem_ThrowUnitPriceGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment has already been paid..
        /// </summary>
        public static string Payment_AlreadyPaid {
            get {
                return ResourceManager.GetString("Payment_AlreadyPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparation is already cancelled..
        /// </summary>
        public static string Preparation_AlreadyCancelled {
            get {
                return ResourceManager.GetString("Preparation_AlreadyCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparation can only be complete if it is in progress..
        /// </summary>
        public static string Preparation_CanOnlyCompleteIfInProgress {
            get {
                return ResourceManager.GetString("Preparation_CanOnlyCompleteIfInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparation can only be deliver if it is completed..
        /// </summary>
        public static string Preparation_CanOnlyDeliverIfCompleted {
            get {
                return ResourceManager.GetString("Preparation_CanOnlyDeliverIfCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparation can only be started if it is pending..
        /// </summary>
        public static string Preparation_CanOnlyStartIfInPending {
            get {
                return ResourceManager.GetString("Preparation_CanOnlyStartIfInPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product CategoryId is not valid.
        /// </summary>
        public static string Product_ThrowCategoryIdInvalid {
            get {
                return ResourceManager.GetString("Product_ThrowCategoryIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The category image file cannot be empty.
        /// </summary>
        public static string Product_ThrowCategoryImageFileIsEmpty {
            get {
                return ResourceManager.GetString("Product_ThrowCategoryImageFileIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product description cannot be empty.
        /// </summary>
        public static string Product_ThrowDescriptionIsEmpty {
            get {
                return ResourceManager.GetString("Product_ThrowDescriptionIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Name cannot empty .
        /// </summary>
        public static string Product_ThrowNameIsEmpty {
            get {
                return ResourceManager.GetString("Product_ThrowNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product price cannot be empty.
        /// </summary>
        public static string Product_ThrowPriceIsGreaterThanZero {
            get {
                return ResourceManager.GetString("Product_ThrowPriceIsGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password hash cannot be empty.
        /// </summary>
        public static string User_PasswordHashIsEmpty {
            get {
                return ResourceManager.GetString("User_PasswordHashIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The role name cannot be empty.
        /// </summary>
        public static string User_RoleIsEmpty {
            get {
                return ResourceManager.GetString("User_RoleIsEmpty", resourceCulture);
            }
        }
    }
}
